config/routes.rb
Rails.application.routes.draw do
  resources :spreadsheets
  root "spreadsheets#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spreadsheet.rb
# == Schema Information
#
# Table name: spreadsheets
#
#  id                 :bigint           not null, primary key
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  dividas_fixas      :text
#  dividas_extras     :text
#  dividas_fixas_val  :integer
#  dividas_extras_val :integer
#  renda_fixa_val     :integer
#  renda_extra_val    :integer
#
class Spreadsheet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/spreadsheets_controller.rb
class SpreadsheetsController < ApplicationController

  def index
    @spreadsheets = Spreadsheet.all
    @spreadsheet = Spreadsheet.new
  end

  def show
    @spreadsheet = Spreadsheet.find(params[:id])
  end

  def new
    @spreadsheet = Spreadsheet.new
  end

  def edit
    @spreadsheet = Spreadsheet.find(params[:id])
  end

  def create
    @spreadsheet = Spreadsheet.new(spreadsheet_params)
      if @spreadsheet.save
        redirect_to spreadsheets_path
      else
        render 'new'
      end
  end

  def update
  	@spreadsheet = Spreadsheet.find(params[:id])
      if @spreadsheet.update(spreadsheet_params)
      else
  		  render 'edit'
  	  end
  end

  def destroy
    @spreadsheet = Spreadsheet.find(params[:id])
    @spreadsheet.destroy
  
    redirect_to spreadsheets_path
  end

  def receita
    Spreadsheet.all.sum('renda_fixa_val + renda_extra_val')
  end

  def despesa
    Spreadsheet.all.sum('dividas_fixas_val + dividas_extras_val')
  end

  def total
    receita + despesa
  end

  private
    def spreadsheet_params
      params.require(:spreadsheet).permit(:dividas_fixas, :dividas_fixas_val,
      :dividas_extras, :dividas_extras_val, :renda_fixa_val, :renda_extra_val)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/spreadsheets_helper.rb
module SpreadsheetsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<ul class="navbar-nav">
	<li class="nav-item text-light mr-3"><%= render 'spreadsheets/form' %></li>  
	<li class="nav-item text-light"></li>
</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Planilha</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/spreadsheets/_form.html.erb
<%= form_with(model: @spreadsheet, html: {class: "form-signin"}, remote: true) do |form| %>
  <div class="hidden">
    <%= form.label :dividas_fixas, "dividas fixas" %>
    <%= form.text_field :dividas_fixas, placeholder: "Gasolina, Alimentação...", class: "form-control" %>
    <%= form.number_field :dividas_fixas_val, placeholder: "100,00", class: "form-control" %>

    <%= form.label :dividas_extras, "dividas extras" %>
    <%= form.text_field :dividas_extras, placeholder: "Acidente...", class: "form-control" %>
    <%= form.number_field :dividas_extras_val, placeholder: "100,00", class: "form-control" %>

    <%= form.label :renda_fixa_val, "renda fixa" %>
    <%= form.number_field :renda_fixa_val, placeholder: "100,00", class: "form-control" %>

    <%= form.label :renda_extra_val, "renda extra" %>
    <%= form.number_field :renda_extra_val, placeholder: "100,00", class: "form-control mb-1" %>
  </div>
    <%= form.submit "Novo", class: "btn btn-md btn-primary btn-block btn-new" %>
<% end %>

app/views/spreadsheets/_tbody.html.erb
<tbody>
      <% @spreadsheets.each do |spreadsheet| %>
      <tr>
      <%= form_with(model: spreadsheet, html: {class: "form-signin #{spreadsheet.id}" }, remote: true) do |form| %>
        <td>
          <%= form.text_field :dividas_fixas, placeholder: " ", class: "form-control" %>
        </td>
        <td>
          <%= form.number_field :dividas_fixas_val, placeholder: "R$ ", class: "form-control" %>
        </td>
        <td>
          <%= form.text_field :dividas_extras, placeholder: " ", class: "form-control" %>
        </td>
        <td>
          <%= form.number_field :dividas_extras_val, placeholder: "R$ ", class: "form-control" %>
        </td>
        <td>
          <%= form.number_field :renda_extra_val, placeholder: "R$ ", class: "form-control" %>
        </td>
        <td>
          <%= form.number_field :renda_fixa_val, placeholder: "R$ ", class: "form-control" %>
        </td>
        <td>
          <%= link_to 'x', spreadsheet_path(spreadsheet), method: :delete, remote: true %>
        </td>
      <% end %></tr>
      <% end %>
</tbody>

app/views/spreadsheets/_update.html.erb
<div class="input-group mb-1">
  <div class="input-group-prepend">
    <span class="input-group-text">R$</span>
  </div>
  <p class="form-control text-muted poop">Receita: </p>
  <p class="form-control text-right text-success"><%= r = Spreadsheet.all.sum('renda_fixa_val + renda_extra_val') %></p>
  <div class="input-group-append">
    <span class="input-group-text">.00</span>
  </div>
</div>
<div class="input-group mb-1">
  <div class="input-group-prepend">
    <span class="input-group-text">R$</span>
  </div>
  <p class="form-control text-muted poop">Despesa: </p>
  <p class="form-control text-right text-danger"><%= d = Spreadsheet.all.sum('dividas_fixas_val + dividas_extras_val')%></p>
  <div class="input-group-append">
    <span class="input-group-text">.00</span>
  </div>
</div>
<div class="input-group mb-1">
  <div class="input-group-prepend">
    <span class="input-group-text">R$</span>
  </div>
  <p class="form-control text-muted">Total: </p>
  <p class="form-control text-right"><%= r - d %></p>
  <div class="input-group-append">
    <span class="input-group-text">.00</span>
  </div>
</div>

app/views/spreadsheets/edit.html.erb
<h1>Editing Spreadsheet</h1>

<%= render 'form', spreadsheet: @spreadsheet %>

<%= link_to 'Show', @spreadsheet %> |
<%= link_to 'Back', spreadsheets_path %>

app/views/spreadsheets/index.html.erb
<table class="table table-striped text-center">
   <thead>
      <tr>
         <th colspan="2">Dividas Fixas</th>
         <th colspan="2">Dividas Extras</th>
         <th>Renda Fixa</th>
         <th>Renda Extra</th>
      </tr>
   </thead>
   <%= render 'spreadsheets/tbody' %>
</table>

<div id="totals-wrapper">
  <%= render 'spreadsheets/update' %>
</div>

app/views/spreadsheets/new.html.erb
<h1 class="text-center mt-2">Nova entrada</h1>

<% if flash[:notice] -%>
  <p class="alert alert-info"><%= flash[:notice] %></p>
<% end -%>

<%= render 'form' %>

<%= link_to 'Voltar', spreadsheets_path %>

app/views/spreadsheets/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_spreadsheet_path(@spreadsheet) %> |
<%= link_to 'Back', spreadsheets_path %>